<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Carry Out Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'suezheng@hotmail.com',
		'to' => 'suezheng@hotmail.com'
	),
	'fields' => array(
		'custom_U413' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'Choose Your Pizza',
			'required' => true,
			'optionItems' => array(
				'Detroit style',
				'Quad City style',
				'Chicago Deep Dish',
				'NEW ENGLAND GREEK',
				'NEW HAVEN “APIZZA”',
				'PHILADELPHIA TOMATO PIE',
				'TRENTON TOMATO PIE',
				'ST. LOUIS STYLE',
				'California Style',
				'Easy Cheesy Stroll',
				'Porchetta Plaza',
				'Gastro Grid',
				'Tavern Taster',
				'Cheesesteak Crawl',
				'Pesto Pretzel Chicken',
				'Greenscape',
				'Philadelphia Tomato Pie',
				'Up ‘n Coming Pepperoni',
				'Hoagie Pizza',
				'Irish Potato',
				'West Indian pepper pot soup',
				'Caesar salad',
				'Arugula salad',
				'Mozzarella sticks',
				'Fruit Beer',
				'Ginger Ale',
				'Vanilla Cream Soda',
				'Iced Tea'
			),
			'errors' => array(
				'required' => 'Field \'Choose Your Pizza\' is required.',
				'format' => 'Field \'Choose Your Pizza\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
