<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Form2 Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'robin.zheng@temple.edu',
		'to' => 'robin.zheng@temple.edu'
	),
	'fields' => array(
		'custom_U2401' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'custom_U2405' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Phone Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone Number\' is required.'
			)
		),
		'custom_U2501' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Custom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Custom\' is required.'
			)
		),
		'custom_U1251' => array(
			'order' => 1,
			'type' => 'checkboxgroup',
			'label' => 'Add Toppings',
			'required' => true,
			'optionItems' => array(
				'Pepperoni',
				'sausage',
				'bacon',
				'ham',
				'chicken',
				'roast beef',
				'salami',
				'anchovies',
				'Mushrooms',
				'green peppers',
				'sweet peppers',
				'jalapeños',
				'spinach',
				'broccoli',
				'Extra cheese',
				'onions',
				'olives',
				'garlic',
				'pineapple',
				'barbecue sauce'
			),
			'errors' => array(
				'required' => 'Field \'Add Toppings\' is required.',
				'format' => 'Field \'Add Toppings\' has an invalid value.'
			)
		),
		'custom_U2459' => array(
			'order' => 3,
			'type' => 'radiogroup',
			'label' => 'Radio Button Group',
			'required' => true,
			'optionItems' => array(
				'South Philadelphia branch',
				'old city branch'
			),
			'errors' => array(
				'required' => 'Field \'Radio Button Group\' is required.',
				'format' => 'Field \'Radio Button Group\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
